# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test Python Package Workflow

on: [push]
# on:
#   push:
#     branches: 
#       - master
#       - dev
#       - stage

# permissions:
#   contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Check Branch and github action
      id: set_env
      run: |
        echo "super_secret: ${{ secrets.SUPERSECRET }}"
        echo "Event Name : ${{github.event_name}}"
        echo "Event Ref : ${{github.ref}}"
        echo "Event Path : ${{github.event_path}}"
        echo "Event Event : ${{github.event}}"
        echo "Workpace : ${{github.workpace}}"
        echo "Workflow : ${{github.workflow}}"

    # - name: Check Branch and github action
    #   id: use_env
    #   run: |
    #     TR_WORKSPEACE="${{set_env.outputs.name}}"
    #     TR_WORKSPEACE=dev

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install build
    #     pip install click==8.1.3
    #     pip install colorama==0.4.5
    #     pip install Flask==2.1.2
    #     pip install itsdangerous==2.1.2
    #     pip install Jinja2==3.1.2
    #     pip install MarkupSafe==2.1.1
    #     pip install Werkzeug==2.1.2
    # - name: Build package
    #   run: python -m build
    # - name: Publish package
    #   uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
    #   with:
    #     user: __token__
    #     password: ${{ secrets.PYPI_API_TOKEN }}
